Update ci.yml to modify Deployment Automation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -13,7 +13,7 @@ jobs:
 
     steps:
     - name: Checkout Code
-      uses:  actions/checkout@v4
+      uses: actions/checkout@v4
 
     - name: Set Up JDK 22
       uses: actions/setup-java@v4
@@ -22,7 +22,7 @@ jobs:
         java-version: '22'
 
     - name: Build with Gradle
-      run: ./gradlew clean build
+      run: ./gradlew build --scan
 
     - name: Upload Build Artifacts
       uses: actions/upload-artifact@v4
@@ -46,10 +46,16 @@ jobs:
       uses: actions/upload-artifact@v4
       with:
         name: jacoco-coverage-report
-        path: app/core/build/reports/jacoco/test/html
+        path: app/core/build/reports/jacoco/test/html/**
 
     - name: Build Docker Image
       run: docker build --no-cache --pull --build-arg VERSION_TAG=alpha -t ${{ secrets.DOCKER_USERNAME }}/stirling-pdf:latest -f ./Dockerfile .
+
+    - name: Run Docker Image for Verification
+      run: |
+        docker run --rm -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/stirling-pdf:latest
+        sleep 10
+        curl -f http://localhost:8080 || (echo "Container failed to start" && exit 1)
 
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
